config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :challenges, only: [:show]
  resources :exercises, only: [:show] do
    resource :leaderboard
    resources :submissions, only: [:create]
  end
  namespace :admin do
    # Add dashboard for your models here
    resources :challenges
    resources :levels
    resources :exercises
    resources :assessments
    resources :result
    resources :invitations

    root to: "challenges#index" # <--- Root route
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :welcome, only: :update, controller: :welcome
  resources :get_started
  # Defines the root path route ("/")
  root "welcome#show"
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def show
    @invitation = Invitation.new
    @invitations = current_user.claimed_invitations
      .includes(
                                 challenge: [levels: [:exercises]]
                               ).order(created_at: :desc)
  end

  def update
    @invitation = Invitation.unclaimed.find_by(code: invitation_params[:code])

    respond_to do |format|
      if @invitation&.update(claimer: current_user)
        format.turbo_stream { flash.now[:notice] = "You've accepted the invitation! 🎉" }
        format.html { redirect_to(root_url) }
      else
        format.turbo_stream { flash.now[:alert] = "Invitatation code is not valid." }
        format.html { redirect_to(root_url, status: :unprocessable_entity) }
      end
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:code)
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/show.html.erb
<div class="container">
  <!--h1 class="font-bold text-4xl">Challenges#index</h1>
    <div class="flex-1">
      <br/>
      <%#= turbo_frame_tag "invitations" do %>
        <%#= render @invitations, user: current_user %>
      <%# end %>
    </div-->

  <div class="flex justify-between w-full">
    <div class="border">
      <div class="mockup-code" style="background-color: initial; color: inherit">
        <pre data-prefix="$"><code>echo "${greeting}"</code></pre>
        <pre data-prefix=">"><code>👋 Welcome <%= current_user.display_name %>!</code></pre>
        <br/>
        <pre data-prefix="$"><code>tree --challenge --all</code></pre>
        <pre data-prefix=">"><code></code></pre>
        <div style="margin-left: 3rem; margin-top: -1.4rem">
          <%= turbo_frame_tag "invitations" do %>
            <%= render @invitations, user: current_user %>
          <% end %>
        </div>
        <br/>
        <pre data-prefix="$"><code>man hello_world</code></pre>
        <pre data-prefix=">"><code>NAME
        hello_world -- fun code Challenges

     DESCRIPTION:
        You can now start working on your first challenge.
        Completing all exercises will put you up on the leaderboard!

        Good luck!</code></pre>
        <br/>
        <pre data-prefix="$"><code>help</code></pre>
        <pre data-prefix=">"><code>Please see the <a class="link">FAQ</a> or contact us at <a href="mailto:hello@world.com" class="link">hello@world.com</a>.</code></pre>
        <!--pre data-prefix="$">
        <div style="margin-left: 3rem; margin-top: -7.6rem">
        <%#= simple_form_for :invitation, url: welcome_path, method: :patch, local: true do |f| %>
            <%#= f.input :code, label: false, placeholder: "enter invitation code", input_html: { value: params[:code], class: "input input-sm input-ghost w-full max-w-xs" }  %>
        <%# end %></div></pre-->
      </div>
    </div>
  </div>
</div>

app/views/welcome/update.turbo_stream.erb
<%= turbo_stream.append "invitations", @invitation %>
<%= render_turbo_stream_flash_messages %>